name: Build

on:
  workflow_call:
    inputs:
      bypassValidation:
        required: false
        type: boolean
        default: false

    outputs:
      docker_tag:
        description: 'Docker image tag'
        value: ${{ jobs.build.outputs.docker_tag }}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v5

      - name: 'Setup node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Verify linting'
        if: ${{ !inputs.bypassValidation }}
        run: npm run lint

      - name: 'Audit dependencies'
        if: ${{ !inputs.bypassValidation }}
        run: npm audit --production --audit-level=high

      - name: 'Verify formatting'
        if: ${{ !inputs.bypassValidation }}
        run: npm run format-check

      - name: 'Build'
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha, prefix=commit-

      - name: Build and push Docker image
        id: docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
