name: Create preview environment

on:
  workflow_dispatch:
    inputs:
      bypassValidation:
        description: 'Bypass validation checks'
        required: false
        default: false
        type: boolean
      targetBranch:
        description: 'Branch name to create preview from'
        required: true
        default: 'main'
        type: string
                
env:
  image_registry: ghcr.io

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.meta.outputs.tags }}
      target_branch_short_name: ${{ steps.get_sanatized_name.outputs.branchname }}
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v6
        with: 
          ref: ${{ github.event.inputs.targetBranch }}
      - name: Get target branch sanatized name
        id: get_sanatized_name
        run: echo "branchname=$(git branch --show-current | sed 's/[^a-z0-9._-]/-/g' | sed 's/^-*//;s/-*$//' | sed 's/-\{2,\}/-/g' | tr '[:upper:]' '[:lower:]' | cut -c1-15)" >> $GITHUB_OUTPUT

      - name: 'Setup node.js'
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Verify linting'
        if: ${{ !github.event.inputs.bypassValidation }}
        run: npm run lint

      - name: 'Audit dependencies'
        if: ${{ !github.event.inputs.bypassValidation }}
        run: npm audit --production --audit-level=high

      - name: 'Verify formatting'
        if: ${{ !github.event.inputs.bypassValidation }}
        run: npm run format-check

      - name: 'Build'
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.get_sha.outputs.sha }},prefix=preview-

      - name: Build and push Docker image
        id: docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec
        id: octo-sts
        with:
          scope: kartverket/tnt-apps
          identity: norgeskart5

      - name: Checkout apps repository
        uses: actions/checkout@v6
        with:
          repository: kartverket/tnt-apps
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}

      - name: Git setup for deploy
        run: |
          git config --global user.email "tnt-nk@kartverket.no"
          git config --global user.name "tnt-nk CI"

      - name: Update deployment
        env:
          COMMIT_MESSAGE: Create preview for branch ${{ needs.build.outputs.target_branch_short_name }}
          NEW_FILE_PATH: env/atgcp1-dev/norgeskart-preview/norgeskart-preview-${{ needs.build.outputs.target_branch_short_name }}.jsonnet
        run: |
          mkdir -p env/atgcp1-dev/norgeskart-preview
          cp -f applications/partials/norgeskart-preview-partial.jsonnet $NEW_FILE_PATH
          sed -i '1ilocal name = "norgeskart-preview-${{ needs.build.outputs.target_branch_short_name }}";' $NEW_FILE_PATH
          sed -i '1ilocal image = "${{ needs.build.outputs.docker_tag }}";' $NEW_FILE_PATH
          sed -i '1ilocal ingress = ["norgeskart-preview-${{ needs.build.outputs.target_branch_short_name }}.atgcp1-dev.kartverket-intern.cloud"];' $NEW_FILE_PATH
          git add .
          git commit -m "$COMMIT_MESSAGE"
          git push
      - name: Add url to  output
        run:  |
          echo "Trykk her snart https://norgeskart-preview-${{ needs.build.outputs.target_branch_short_name }}.atgcp1-dev.kartverket-intern.cloud" >> $GITHUB_STEP_SUMMARY
